### PR TITLE
MODULES-1555 Include NoRestart Parameter and Quiet to ensure no prompt

### PR DESCRIPTION
**Pull request by cyberious**
for user input

### CODE REVIEW

**Comment by tphoney** [comment]
@cyberious do you still want this merged ?

**Comment by ferventcoder** [comment]
I just noticed we removed the idea of a NOTICE file when the LICENSE file was updated. The NOTICE file is also important and should stick around.

**Comment by cyberious** [comment]
We didn't remove the NOTICE file and we are actually keeping the same license but actually pasting in what the license actually is rather than short cutting.

**Comment by ferventcoder** [comment]
Right, that's why I stated the **idea of** a NOTICE file, which is what was in the LICENSE file previously.

**Comment by cyberious** [comment]
Had to fix some merge conflicts

**Pull request merged**
